### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by nan2088** [openppl-public/ppl.cv#114]
## What are the problems?(snapshots or detailed error messages)
use ppl::cv::cuda::Resize<uchar, 3> to resize 
INPUT:
[[[0, 0, 0]], [[1, 0, 0]], [[1, 0, 0]]], uchar, src_stride == 9
to
 (224,224) dst_stride == 3*224

result ：
RC_DEVICE_RUNTIME_ERROR (an illegal memory access was encountered)

## Which version(commit id or tag) of ppl.cv is used?
master

# EDIT
my own fault

**Comment by lucky-dersan** [comment]
how to solve it? i come same question!
