### ISSUE TITLE
build with cuda12 failed

### ISSUE THREAD

**Issue by AncientRemember** [openppl-public/ppl.cv#132]
[ 98%] Building CUDA object CMakeFiles/pplcv_static.dir/src/ppl/cv/cuda/transpose.cu.o
/src/ppl/cv/cuda/warp.hpp(25): error: texture is not a template
  static texture<uchar, 0x02,
         ^

/ppl.cv/src/ppl/cv/cuda/warp.hpp(27): error: texture is not a template
  static texture<uchar4, 0x02,
         ^

ppl.cv/src/ppl/cv/cuda/warp.hpp(29): error: texture is not a template
  static texture<float, 0x02,
         ^

/ppl.cv/src/ppl/cv/cuda/warp.hpp(31): error: texture is not a template
  static texture<float4, 0x02,
         ^

/ppl.cv/src/ppl/cv/cuda/warp.hpp(72): error: no instance of overloaded function "tex2D" matches the argument list
            argument types are: (<error-type>, float, float)
          float value = tex2D(uchar_c1_ref, src_x + 0.5f, src_y + 0.5f);

**Comment by jimurk** [comment]
The texture memory used in ppl.cv cuda isn't supported in CUDA 12, we will support CUDA 12 in the near future.

**Comment by nan2088** [comment]
> The texture memory used in ppl.cv cuda isn't supported in CUDA 12, we will support CUDA 12 in the near future.

Hi，How is the support progress for CUDA 12
