### ISSUE TITLE
trivial case in CUDA resize not synchronized with stream argument

### ISSUE THREAD

**Issue by lzhangzz** [openppl-public/ppl.cv#70]
The `stream` argument is not passed to the following `cudaMemcpyAsync` when handling trivial cases. Causing the copy to be performed on the default stream instead of the passed one.
https://github.com/openppl-public/ppl.cv/blob/eebdbd8ef1e831fa09079cf061752a8695b5dd02/src/ppl/cv/cuda/resize.cu#L1034-L1035
https://github.com/openppl-public/ppl.cv/blob/eebdbd8ef1e831fa09079cf061752a8695b5dd02/src/ppl/cv/cuda/resize.cu#L1228-L1229

**Comment by jimurk** [comment]
thanks, we will fix this in the next update.
