### ISSUE TITLE
请问这个项目的未来规划是什么？

### ISSUE THREAD

**Issue by libaineu2004** [openppl-public/ppl.cv#75]
请问这个项目的未来规划是什么？是把OpenCV已有的算子全部优化实现一遍吗？
什么时候实施canny和templatematch算子？
尤其是opencv的模板匹配templatematch算子比较弱。有无优化拓展（支持旋转，缩放）的计划？

**Comment by jimurk** [comment]
我们这个项目目前规划是满足商汤各业务线的cv需求，包括支持的算子和硬件平台。考虑到opencv是cv行业得到了广泛的认可和采用，我们在opencv已有实现的基础上做进一步优化，算子的接口和结果对齐opencv，但时间和精力有限，不会把opencv完全都优化一遍。
对于canny和templatematch算子，目前没有规划。对于大家有需求但目前我们公司内部暂无需求的算子的支持，我先反馈一下。

**Comment by libaineu2004** [comment]
> 我们这个项目目前规划是满足商汤各业务线的cv需求，包括支持的算子和硬件平台。考虑到opencv是cv行业得到了广泛的认可和采用，我们在opencv已有实现的基础上做进一步优化，算子的接口和结果对齐opencv，但时间和精力有限，不会把opencv完全都优化一遍。 对于canny和templatematch算子，目前没有规划。对于大家有需求但目前我们公司内部暂无需求的算子的支持，我先反馈一下。

那请问商汤有无自己实现的2d图像模板匹配算子？例如，形状匹配和NCC匹配？有无开源？
谢谢！

**Comment by jimurk** [comment]
我们组这边目前没有图像模板匹配算子相关的开发。

**Comment by libaineu2004** [comment]
请问这个链接是国内的镜像吧？怎么仓库和github不是同步的？
https://gitee.com/openppl-public/ppl.cv

**Comment by ouonline** [comment]
是镜像，不过是手动同步的，有延迟

**Comment by libaineu2004** [comment]
请问这个项目的未来规划是什么？还准备新增哪些算子？

**Comment by jimurk** [comment]
下一步的规划是继续增加支持的硬件平台和函数，进一步优化现有函数。函数是商汤业务线所需，具体以更新为准。

**Comment by libaineu2004** [comment]
请问如果显卡配置还可以，那么cuda和simd指令集加速，这两个方法，哪个算子运算的效率会更好？
