### ISSUE TITLE
windows cuda版本支持?

### ISSUE THREAD

**Issue by dengxbin** [openppl-public/ppl.cv#77]
## What are the problems?(snapshots or detailed error messages)
windows vscode 编译 只生成了pplcommon_static.lib

## Which version(commit id or tag) of ppl.cv is used?
main branch

## What's the operating system ppl.cv runs on?
windows 

## What's the compiler and its version?
vs2019 amd 64

## What are the commands used to build ppl.cv?
cmake  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install  -DHPCC_USE_CUDA=ON cmake --build . -j --config Release

**Comment by dengxbin** [comment]
mmdeploy cuda版本编译依赖ppl.cv cuda版本，目前mmdeploy支持了windows编译，ppl.cv是不是还未支持windows编译？

**Comment by jimurk** [comment]
ppl.cv支持windows编译，编译命令是“`$ ./build.bat -G "Visual Studio 16 2019" -A x64 -DHPCC_USE_CUDA=ON`”，你用这个命令编译一下看看。

**Comment by jimurk** [comment]
我增加了一个文档--CUDA Platform Guide，里面有windows编译的说明。
