### ISSUE TITLE
find_package not found

### ISSUE THREAD

**Issue by ywfwyht** [openppl-public/ppl.cv#82]
## What are the problems?(snapshots or detailed error messages)
Installed the pplcv following the tutorial, but find package was not found.

error message:
By not providing "Findpplcv.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "pplcv", but CMake did not find one.

Could not find a package configuration file provided by "pplcv" with any of the following names:
pplcvConfig.cmake
pplcv-config.cmake

add the installation prefix of "pplcv" to CMAKE_PREFIX_PATH or set "pplcv_DIR" to a directory containing one of the above files. If "pplcv" provides a separate development package or SDK, be sure it has been installed.

## Which version(commit id or tag) of ppl.cv is used?
v0.6.2 and latest

## What's the operating system ppl.cv runs on?
ubuntu18.04

## What's the compiler and its version?
gcc7
## What are the commands used to build ppl.cv?
mmdeploy

**Comment by ouonline** [comment]
> add the installation prefix of "pplcv" to CMAKE_PREFIX_PATH or set "pplcv_DIR" to a directory containing one of the above files. If "pplcv" provides a separate development package or SDK, be sure it has been installed.

Did you set `pplcv_DIR` before `find_package`?

**Comment by ywfwyht** [comment]
@ouonline echo ${PPLCV_DIR} ， The path output is correct

**Comment by ouonline** [comment]
> @ouonline echo ${PPLCV_DIR} ， The path output is correct

set `pplcv_DIR` in `CMakeLists.txt`:

```cmake
set(pplcv_DIR /path/to/install/lib/cmake/ppl)
```

not the bash environment.

**Comment by ywfwyht** [comment]
@ouonline thanks
