### ISSUE TITLE
请问如果显卡配置还可以，那么cuda和simd指令集加速，这两种方法，哪个算子运算的效率会更好？

### ISSUE THREAD

**Issue by libaineu2004** [openppl-public/ppl.cv#86]
请问如果显卡配置还可以，那么cuda和simd指令集加速，这两种方法，哪个算子运算的效率会更好？
请不必考虑硬件配置的差异，假设它的显卡和CPU都很高端，纯粹从理论上分析和比较这两种方法。

**Comment by ouonline** [comment]
> 请问如果显卡配置还可以，那么cuda和simd指令集加速，这两种方法，哪个算子运算的效率会更好？ 请不必考虑硬件配置的差异，假设它的显卡和CPU都很高端，纯粹从理论上分析和比较这两种方法。

“配置还可以” 和 “很高端” 这两个条件就自相矛盾了。请问这个是老师留给你的作业题你来求答案的么？（如果我猜错了请原谅我的恶意揣度）

**Comment by libaineu2004** [comment]
> 

没别的意思。就是问一下这两种方法，哪个算子运算的效率会更好？不考虑CPU和GPU选型。

**Comment by jimurk** [comment]
我们这边时间精力有限，没有做效率方面的理论研究。不过，ppl.cv每个函数都有benchmark，你对哪个函数赶兴趣，可以跑跑benchmark，看一下性能。
