### ISSUE TITLE
如果指定线程数？

### ISSUE THREAD

**Issue by huanyingjun** [openppl-public/ppl.cv#91]
看了arm的代码，似乎都是用的单线程跑的，请问一下有没有多线程？如何指定线程数？

**Comment by aboluock** [comment]
是的，pplcv arm和x86都是只支持单线程的

**Comment by huanyingjun** [comment]
谢谢回复，请问有计划支持多线程吗？

**Comment by huanyingjun** [comment]
我在手机上跑了resize性能，单线程是比opencv快，但当opencv用多线程，opencv就比ppl快了。
请问有计划支持多线程吗？

**Comment by aboluock** [comment]
目前短期内还没有支持多线程的计划
