### ISSUE TITLE
build failed saying "No SOURCES given to target: pplcv_static"

### ISSUE THREAD

**Issue by huanghaifeng1234** [openppl-public/ppl.cv#95]
## What are the problems?(snapshots or detailed error messages)
build failed
![image](https://user-images.githubusercontent.com/81546069/175867962-f60f39c8-9bd5-4b37-b175-c3ef04f3efe9.png)

## Which version(commit id or tag) of ppl.cv is used?
master branch

## What's the operating system ppl.cv runs on?
windows 11

## What's the compiler and its version?
Visual Studio 16 2019 Win64

## What are the commands used to build ppl.cv?
build.bat -G "Visual Studio 16 2019 Win64" -DPPLCV_USE_X86_64=ON

## What are the execution commands?
build.bat -G "Visual Studio 16 2019 Win64" -DPPLCV_USE_X86_64=ON

**Comment by ouonline** [comment]
> ## What are the commands used to build ppl.cv?
> build.bat -G "Visual Studio 16 2019 Win64" -DPPLCV_USE_X86_64=ON

vs2019 should use `-A` option to specify the target platform:

```
build.bat -G "Visual Studio 16 2019" -A x64 -DPPLCV_USE_X86_64=ON
```
