### ISSUE TITLE
[Feature] Could ppl.cv support 'bicubic' resize?

### ISSUE THREAD

**Issue by lvhan028** [openppl-public/ppl.cv#99]
MMDeploy inference SDK failed to perform swin-transform inference on CUDA platform because ppl.cv doesn't support 'bicubic' resize

https://github.com/open-mmlab/mmclassification/blob/2495400a98a3da9bd8cfb3731a711f4c77cc56a3/configs/_base_/datasets/imagenet_bs64_swin_224.py#L46

**Comment by jimurk** [comment]
resize支持线性插值等三种常用插值方法，目前不支持bicubic，具体支持的插值方法参见resize.h里的文档。

**Comment by lvhan028** [comment]
有支持的计划吗？

**Comment by jimurk** [comment]
暂时没有。
